FROM node:18

WORKDIR /app

COPY . .

ENV DATABASE_URL=${DATABASE_URL}
ENV JSON_TOKEN_KEY=${JSON_TOKEN_KEY}

RUN npm install

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]