version: '1.0'
services:         
  postgres:
      image: postgres:15.5
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 102030
        POSTGRES_DB: athena
      ports:
        - 5555:5432

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      JSON_TOKEN_KEY: ${JSON_TOKEN_KEY}
    ports:
      - "3000:3000"
    working_dir: /app
    command: bash -c "npx prisma migrate deploy && npx prisma db seed && npm run start:prod"
