version: '1.0'
services:       
  postgres:
      image: postgres:15.5
      environment:
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      ports:
        - 5433:5432

  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      JSON_TOKEN_KEY: ${JSON_TOKEN_KEY}
    ports:
      - "3000:3000"
    working_dir: /app
    entrypoint: /app/entrypoint.sh
