name: Continous Integration

on: [push, pull_request]

jobs:
  continous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: run install, build and test
        run: |
          npm install
          npx prisma generate
          # Configurar banco de dados PostgreSQL
          uses: actions/setup-database@v1
          with:
            database: my-database
            user: my-user
            password: my-password
            engine: postgres
            createDatabase: true
          npx prisma migrate dev
          npm run test
          npm run build