name: Continous Integration

on: [push, pull_request]


jobs:
  continous-integration:
    runs-on: ubuntu-latest

    services:         
      postgres:
        image: postgres:15.5
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: run install, build and test
        run: npm install

      - name: Connect to postgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: athena
      
      - name: run prisma generate
        run: npx prisma generate  

      - name: run prisma migrations
        run: npx prisma migrate deploy

      - name: run tests
        run: npm run test

      - name: run build
        run: npm run build