name: Continous Intergration

on: [pull_request, push]

jobs:
  continous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: run install, build and test
        run: |
          npm install
          npx prisma generate
          npm run test 
          npm run build 