name: Continous Integration

on:
  push:
    branches:
      - master

jobs:
  continous-integration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 102030
          POSTGRES_DB: athena
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: run install, build and test
        run: npm install

      - name: run prisma generate
        run: npx prisma generate

      - name: run prisma migrations
        run: npx prisma migrate dev
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}

      - name: run tests
        run: npm run test
        env:
          JSON_TOKEN_KEY: ${{secrets.JSON_TOKEN_KEY}}
      - name: run build
        run: npm run build

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: continous-integration
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-secret "DATABASE_URL=${{secrets.FLY_DATABASE_URL}} JSON_TOKEN_KEY=${{secrets.JSON_TOKEN_KEY}}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
