name: Continous Intergration

on: [pull_request, push]

env:
  DATABASE_URL: postgresql://postgres:102030@host.docker.internal:5555/athena?schema=public

jobs:
  continous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: ./.github/actions/docker-compose
      - name: Run tests
        run: npm run test
